name: release

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3

    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        environment-file: conda/dev.yaml
        channels: conda-forge,nodefaults
        activate-environment: epigraphhubpy
        auto-update-conda: true
        conda-solver: libmamba
        python-version: "${{ matrix.python_version }}"

    - name: Install dependencies
      run: poetry install

    - name: Test Release
      if: ${{ github.event_name != 'workflow_dispatch' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: makim release.dry-run

    - name: Release
      if: ${{ github.event_name == 'workflow_dispatch' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry config pypi-token.pypi ${PYPI_TOKEN}
        makim release.ci
